application:
  base_url: "https://tommie-bronchiectatic-unmathematically.ngrok-free.dev"
  admin_url: "https://tommie-bronchiectatic-unmathematically.ngrok-free.dev/admin"

selenium:
  browser: "chrome"
  headless: true
  implicit_wait: 10
  page_load_timeout: 30
  window_width: 1920
  window_height: 1080

credentials:
  admin_username: "admin"
  admin_password: "admin"
  customer_email: "test@example.com"
  customer_password: "test123"

test_settings:
  screenshot_folder: "reports/screenshots"
  screenshot_on_failure: true
  parallel_workers: 1